# Generated by Django 4.1.5 on 2023-02-07 11:57

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingname', models.CharField(max_length=255)),
                ('description', models.TextField(default='Nav apraksta', max_length=2000)),
                ('listingimage', models.ImageField(default='images/default.png', upload_to='images/', validators=[store.models.validate_image])),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=255)),
                ('statuscompleted', models.BooleanField(default=False)),
                ('listinguser', models.CharField(max_length=255)),
            ],
        ),
    ]
