# Generated by Django 4.1.4 on 2023-01-14 17:50

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default='Nav apraksta', max_length=2000),
        ),
        migrations.AddField(
            model_name='listing',
            name='listingimage',
            field=models.ImageField(default='images/default.png', upload_to='images/', validators=[store.models.validate_image]),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='statuscompleted',
            field=models.BooleanField(default=False),
        ),
    ]
