# Generated by Django 4.1.4 on 2023-01-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_listing_description_listing_listingimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.CharField(default='EUR', max_length=255),
        ),
    ]
